baseURL = 'https://www.ambitious-i.net/'
languageCode = 'ja-jp'
title = '鰯の管詰'

canonifyURLs=true
pluralizeListTitles = false
summaryLength = 25
theme = "BlogRa"

[params]
    description     = "職業：エンジニアの気づき・趣味・ポエムをまとめたサイトです♪日々生活する中で、誰かに奴立つ情報が発信できれば嬉しいです(^^)"
    footer          = ""
    googleSearch    = "google-cse-key"
    googleAnalytics = "G-A1B2C3D4E5" # v4

    twitter    = "https://twitter.com/ninjinx"
    github     = "https://github.com/bvlion"
    facebook   = ""
    youtube    = ""
    instagram  = ""
    pinterest  = ""
    linkedin   = ""

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Posts"
                url = "/posts/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "divider"
                weight = 3
            [[menu.main]]
                parent = "blog"
                name = "Tags"
                url = "/tags/"
                weight = 4
    [[menu.main]]
        identifier = "about"
        name = "About"
        weight = 3
            [[menu.main]]
                parent = "about"
                name = "本人について"
                url = "/person/"
                weight = 1
            [[menu.main]]
                parent = "about"
                name = "アカウント"
                url = "/account/"
                weight = 2
            [[menu.main]]
                parent = "about"
                name = "個人活動"
                url = "https://bvlion-app.web.app"
                weight = 3
    [[menu.main]]
        name = "ご意見・ご感想"
        url = "https://forms.gle/dUkf1dNdkgN2ZxJ66"
        weight = 4

# Don't touch this
[markup.goldmark.renderer]
    unsafe = true